// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOm_We6ljgfiYL6-xXU2NOWpYwphUOLLM',
    appId: '1:675190007449:web:53c24b0ff96589bc7c7a08',
    messagingSenderId: '675190007449',
    projectId: 'flutter-controle-de-veiculos',
    authDomain: 'flutter-controle-de-veiculos.firebaseapp.com',
    storageBucket: 'flutter-controle-de-veiculos.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApmT90oq4KW3-oC5A5AR0bEwPV7u6Wxyg',
    appId: '1:675190007449:android:46165ac1938cb4d47c7a08',
    messagingSenderId: '675190007449',
    projectId: 'flutter-controle-de-veiculos',
    storageBucket: 'flutter-controle-de-veiculos.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOm_We6ljgfiYL6-xXU2NOWpYwphUOLLM',
    appId: '1:675190007449:web:ec43969db69ea23e7c7a08',
    messagingSenderId: '675190007449',
    projectId: 'flutter-controle-de-veiculos',
    authDomain: 'flutter-controle-de-veiculos.firebaseapp.com',
    storageBucket: 'flutter-controle-de-veiculos.firebasestorage.app',
  );

}